Repository Vaskivskyi/ha-asusrouter, pull requests merged in 2022-12, with the labels that each got.

#358 Bump asusrouter to 0.12.1
  custom_components/asusrouter/manifest.json
Labels: dependencies

#359 Add `remove_trackers` service
  custom_components/asusrouter/device_tracker.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/services.yaml
Labels: enhancement

#360 Bump asusrouter to 0.13.0
  custom_components/asusrouter/manifest.json
Labels: dependencies

#361 Bump version to 0.14.0
  custom_components/asusrouter/manifest.json
Labels: build

#362 Move stable branch to 0.14.0
  custom_components/asusrouter/device_tracker.py
  custom_components/asusrouter/manifest.json
  custom_components/asusrouter/router.py
  custom_components/asusrouter/services.yaml
Labels: build

#364 Bump version to 0.14.1
  custom_components/asusrouter/manifest.json
Labels: build

#365 Move stable branch to 0.14.1
  custom_components/asusrouter/manifest.json
  custom_components/asusrouter/translations/es.json
Labels: build

#366 Add French translation
  custom_components/asusrouter/translations/fr.json
Labels: translation

#367 cs.json
  custom_components/asusrouter/translations/cs.json
Labels: translation

#368 Bump version to 0.14.2
  custom_components/asusrouter/manifest.json
Labels: build

#373 New Slovak language - sk.json
  custom_components/asusrouter/translations/sk.json
Labels: translation

#374 Bump version to 0.14.3
  custom_components/asusrouter/manifest.json
Labels: build

#376 Move stable branch to 0.14.3
  custom_components/asusrouter/manifest.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
Labels: build

#377 Add `guest_id` attribute to the device identity
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
Labels: enhancement

#378 Update with black
  custom_components/asusrouter/router.py
Labels: refactoring

#379 Update build badge in the readme
  README.md
Labels: github

#380 Remove deprecated from `asusrouter.device_internet_access` service
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/services.yaml
Labels: breaking

#381 Remove migration from versions 0.5.1 and lower
  custom_components/asusrouter/__init__.py
  custom_components/asusrouter/migrate.py
Labels: breaking

#382 Cleanup
  custom_components/asusrouter/__init__.py
Labels: refactoring

#385 Update temperature features
  custom_components/asusrouter/const.py
  custom_components/asusrouter/sensor.py
  hacs.json
Labels: enhancement, breaking

#386 Add HA `integration_type`
  custom_components/asusrouter/manifest.json
Labels: enhancement

#387 Switch to `SourceType` enum
  custom_components/asusrouter/device_tracker.py
Labels: enhancement

#388 Update release drafter
  .github/release-drafter.yml
Labels: github

#389 Bump asusrouter to 0.14.0
  custom_components/asusrouter/manifest.json
Labels: dependencies

#390 Bump version to 0.15.0
  custom_components/asusrouter/manifest.json
Labels: build

#391 Add Dutch translation
  custom_components/asusrouter/translations/nl.json
Labels: translation

#392 Minor fix in Dutch translation
  custom_components/asusrouter/translations/nl.json
Labels: translation

#393 Bump version to 0.15.1
  custom_components/asusrouter/manifest.json
Labels: build

#394 Move stable branch to 0.15.1
  .github/release-drafter.yml
  README.md
  custom_components/asusrouter/__init__.py
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/device_tracker.py
  custom_components/asusrouter/manifest.json
  custom_components/asusrouter/migrate.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/sensor.py
  custom_components/asusrouter/services.yaml
  custom_components/asusrouter/translations/nl.json
  hacs.json
Labels: build

#395 Simplify obtaining of temperature sensors list from the backend
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/helpers.py
Labels: refactoring

#396 Simplify code for load_avg sensors
  custom_components/asusrouter/const.py
  custom_components/asusrouter/sensor.py
Labels: refactoring

#397 Simplify code for static sensors
  custom_components/asusrouter/const.py
  custom_components/asusrouter/sensor.py
Labels: refactoring

#398 Simplify code for static binary sensors
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/const.py
Labels: refactoring

#399 Simplify code for static buttons
  custom_components/asusrouter/button.py
  custom_components/asusrouter/const.py
Labels: refactoring

#400 Simplify code for static lights
  custom_components/asusrouter/const.py
  custom_components/asusrouter/light.py
Labels: refactoring

#401 Simplify code for static switches
  custom_components/asusrouter/const.py
  custom_components/asusrouter/switch.py
Labels: refactoring

#402 Simplify code for static updates
  custom_components/asusrouter/const.py
  custom_components/asusrouter/update.py
Labels: refactoring

#403 Improve constants usage
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
Labels: refactoring

#404 Improve static sensors
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/switch.py
Labels: refactoring

#405 Improve constants usage
  custom_components/asusrouter/const.py
  custom_components/asusrouter/dataclass.py
Labels: refactoring

#406 Improve hiding of protected sensor attributes
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/entity.py
  custom_components/asusrouter/switch.py
Labels: enhancement

#407 Move the `no-control` features to the integration only
  custom_components/asusrouter/bridge.py
Labels: enhancement

#408 Allow only in `control` mode `adjust_wlan` and `device_internet_access`
  custom_components/asusrouter/router.py
Labels: enhancement, breaking

#409 Bump asusrouter to 0.15.0
  custom_components/asusrouter/manifest.json
Labels: dependencies

#410 Remove the confirmation step from config flow
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
Labels: enhancement

#411 Bump version to 0.16.0
  custom_components/asusrouter/manifest.json
Labels: build

#412 Bump asusrouter to 0.15.1
  custom_components/asusrouter/manifest.json
Labels: dependencies

#413 Move stable branch to 0.16.0
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/button.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/dataclass.py
  custom_components/asusrouter/entity.py
  custom_components/asusrouter/helpers.py
  custom_components/asusrouter/light.py
  custom_components/asusrouter/manifest.json
  custom_components/asusrouter/router.py
  custom_components/asusrouter/sensor.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/switch.py
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
  custom_components/asusrouter/update.py
Labels: build

#415 Update the supported devices list
  README.md
Labels: documentation

#416 Bump asusrouter to 0.15.2
  custom_components/asusrouter/manifest.json
Labels: dependencies

#417 Bump version to 0.16.1
  custom_components/asusrouter/manifest.json
Labels: build
