Repository Vaskivskyi/ha-asusrouter, pull requests merged in 2022-05, with the labels that each got.

#8 Bump version to 0.1.5
  custom_components/asusrouter/manifest.json
Labels: build

#9 Add HACS default installation to Readme
  README.md
Labels: documentation

#13 Add translation to release-drafter
  .github/release-drafter.yml
Labels: github

#11 Add Brazilian Portuguese Translation
  custom_components/asusrouter/translations/pt-BR.json
Labels: translation

#12 Add credits to HA AsusWRT and ollo69/ha_asuswrt_custom
  README.md
Labels: documentation

#14 Select interfaces for traffic monitoring
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/dataclass.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/sensor.py
  custom_components/asusrouter/sensor_helpers.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/en.json
Labels: enhancement

#17 Code cleanup
  custom_components/asusrouter/__init__.py
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/dataclass.py
  custom_components/asusrouter/migrate.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/sensor.py
Labels: refactoring

#18 Update translations to current scheme
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/pt-BR.json
Labels: translation

#19 Add Ukrainian translation
  custom_components/asusrouter/translations/uk.json
Labels: translation

#20 Prepare for AsusRouter 0.3.0 release
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/router.py
Labels: bug, breaking, dependencies

#21 Ports speed sensors for WAN/LAN
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/dataclass.py
  custom_components/asusrouter/sensor.py
Labels: enhancement

#22 Fix migration to 0.2.0
  custom_components/asusrouter/__init__.py
Labels: bug

#23 Fix migration
  custom_components/asusrouter/__init__.py
Labels: bug

#24 Bump asusrouter to 0.3.0
  custom_components/asusrouter/manifest.json
Labels: dependencies

#25 Bump version to 0.2.0
  custom_components/asusrouter/manifest.json
Labels: build

#26 Update documentation for 0.2.0 release
  README.md
  info.md
Labels: documentation

#31 Add info on missing WAN sensors for some devices [issue #30]
  README.md
Labels: documentation

#33 [Docs] Add dashboards examples
  docs/Fig-Dashboard-1.png
  docs/Fig-Dashboard-2.png
  docs/dashboards.md
Labels: documentation

#36 Bump version to 0.2.2
  custom_components/asusrouter/manifest.json
Labels: build

#37 Bump asusrouter to 0.3.2
  custom_components/asusrouter/manifest.json
Labels: dependencies

#38 Bump version to 0.2.3
  custom_components/asusrouter/manifest.json
Labels: build

#39 [Multiple device support] Fix router unique_id assignment
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/config_flow.py
Labels: bug

#41 Fix timezone shift in device_tracker "Connection time" attribute
  custom_components/asusrouter/router.py
Labels: bug

#43 Fix Connected devices sensor from showing offline devices
  custom_components/asusrouter/router.py
Labels: bug

#44 Bump version to 0.2.4
  custom_components/asusrouter/manifest.json
Labels: build

#46 Add supported devices list to readme
  README.md
Labels: documentation

#51 Switch to asusrouter 0.4.0
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/manifest.json
Labels: dependencies

#52 Bump asusrouter to 0.4.1
  custom_components/asusrouter/manifest.json
Labels: dependencies

#53 Simplify config flow
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/en.json
Labels: enhancement

#54 New `wan_ip` sensor
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/sensor.py
Labels: enhancement

#55 Add documentation on the integration setup
  docs/Fig-Setup/Step-1.png
  docs/Fig-Setup/Step-2.png
  docs/Fig-Setup/Step-2b.png
  docs/Fig-Setup/Step-3.png
  docs/Fig-Setup/Step-4.png
  docs/Fig-Setup/Step-5.png
  docs/setup.md
Labels: documentation

#56 Move most of the configs to options and allow to change them via the `Configure` button
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/en.json
Labels: enhancement, breaking

#57 Small optimizations for connected devices
  custom_components/asusrouter/router.py
Labels: performance

#58 Select `cache_time`, `scan_interval` and `consider_home` manually
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/en.json
Labels: enhancement

#59 Cleanup AsusRouter bridge
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/router.py
Labels: refactoring

#60 Remove deprecated `domains` from HACS manifest
  hacs.json
Labels: build

#61 Remove deprecated `iot_class` from HACS manifest
  hacs.json
Labels: build

#62 Add Build badge to README
  README.md
Labels: documentation

#63 Cleanup AsusRouterBridge
  custom_components/asusrouter/bridge.py
Labels: refactoring

#64 Add WAN status `binary_sensor`
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/dataclass.py
Labels: enhancement

#65 Code cleanup
  custom_components/asusrouter/__init__.py
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/dataclass.py
  custom_components/asusrouter/device_tracker.py
  custom_components/asusrouter/diagnostics.py
  custom_components/asusrouter/migrate.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/sensor.py
Labels: refactoring

#66 Bump asusrouter to 0.4.2
  custom_components/asusrouter/manifest.json
Labels: dependencies

#67 Add LED control as `light` entity
  custom_components/asusrouter/const.py
  custom_components/asusrouter/dataclass.py
  custom_components/asusrouter/light.py
Labels: enhancement

#68 Bump asusrouter to 0.4.3
  custom_components/asusrouter/manifest.json
Labels: dependencies

#69 Fix config flow for options showing `time constants` step when not se…
  custom_components/asusrouter/config_flow.py
Labels: bug

#70 Lock `enable_monitor` as `True` until it is completely implemented
  custom_components/asusrouter/config_flow.py
Labels: enhancement

#71 Get LED state on the `light` initialization
  custom_components/asusrouter/light.py
Labels: enhancement

#72 Fix EN translation
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/en.json
Labels: translation

#74 Update Ukrainian translation to the new config flow
  custom_components/asusrouter/translations/uk.json
Labels: translation

#75 Add migration to version 0.3.0
  custom_components/asusrouter/__init__.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/migrate.py
Labels: enhancement

#76 Add New Brazilian Portuguese Translation
  custom_components/asusrouter/translations/pt-BR.json
Labels: translation

#77 Update setup docs
  docs/Fig-Setup/Step-3.png
  docs/Fig-Setup/Step-4.png
  docs/Fig-Setup/Step-5.png
  docs/Fig-Setup/Step-6.png
  docs/Fig-Setup/Step-Options-Confirm.png
  docs/Fig-Setup/Step-Options-Select.png
  docs/setup.md
Labels: documentation

#78 Update documentation
  README.md
  info.md
Labels: documentation

#79 Bump version to 0.3.0
  custom_components/asusrouter/manifest.json
Labels: build

#81 Add Community forum badge
  README.md
  info.md
Labels: documentation

#84 Improve code as per HA Style guidelines
  custom_components/asusrouter/__init__.py
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/dataclass.py
  custom_components/asusrouter/device_tracker.py
  custom_components/asusrouter/diagnostics.py
  custom_components/asusrouter/light.py
  custom_components/asusrouter/migrate.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/sensor.py
Labels: refactoring

#86 Improve string formatting
  custom_components/asusrouter/__init__.py
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/light.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/sensor.py
Labels: refactoring

#87 Bump asusrouter to 0.4.4
  custom_components/asusrouter/manifest.json
Labels: dependencies

#88 Bump version to 0.3.1
  custom_components/asusrouter/manifest.json
Labels: build

#90 Improve data validation in config flow
  custom_components/asusrouter/config_flow.py
Labels: enhancement
