Repository Vaskivskyi/ha-asusrouter, pull requests merged in 2023-01, with the labels that each got.

#418 Add base AiMesh support
  custom_components/asusrouter/__init__.py
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
Labels: enhancement

#419 Add `wired` connection type for AiMesh nodes
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
Labels: enhancement

#420 Improve `connected via` for AiMesh nodes
  custom_components/asusrouter/binary_sensor.py
Labels: enhancement

#421 Fix MAC formatting
  custom_components/asusrouter/router.py
Labels: enhancement

#422 Add AiMesh node events
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
Labels: enhancement

#423 Fix `via_device` attribute for nodes
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/router.py
Labels: bug

#424 Sort entities attributes by alphabet
  custom_components/asusrouter/device_tracker.py
  custom_components/asusrouter/entity.py
Labels: enhancement

#426 Add AiMesh node info to the device identity
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
Labels: enhancement

#427 Bump `asusrouter` to `0.16.0`
  custom_components/asusrouter/manifest.json
Labels: dependencies

#428 Update badges
  README.md
Labels: documentation

#429 Switch to new enums (2022.1.0+)
  custom_components/asusrouter/const.py
  hacs.json
Labels: breaking

#430 Code cleanup
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/update.py
Labels: refactoring

#431 Add AiMesh sensor
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
Labels: enhancement

#432 Add device modes
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
Labels: enhancement, AiMesh

#433 Improve switching between modes
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/router.py
Labels: enhancement

#434 Improve labels in config flow
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
Labels: enhancement

#435 Fix temperature sensors naming
  custom_components/asusrouter/const.py
Labels: bug, breaking

#436 Improve device trackers unique ID
  custom_components/asusrouter/device_tracker.py
  custom_components/asusrouter/router.py
Labels: bug, enhancement

#437 Fix unique_id for all entities
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/entity.py
  custom_components/asusrouter/helpers.py
  custom_components/asusrouter/router.py
Labels: enhancement

#438 Remove alias from AiMesh device name
  custom_components/asusrouter/binary_sensor.py
Labels: enhancement

#439 Rename network interfaces to be more obvious
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
Labels: enhancement

#440 Fix events options
  custom_components/asusrouter/router.py
Labels: bug

#441 Add node events configs
  custom_components/asusrouter/const.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
Labels: enhancement

#442 Bump version to 0.17.0
  custom_components/asusrouter/manifest.json
Labels: build

#444 Bump stable branch to 0.17.0
  .github/workflows/release-drafter.yml
  README.md
  custom_components/asusrouter/__init__.py
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/device_tracker.py
  custom_components/asusrouter/entity.py
  custom_components/asusrouter/helpers.py
  custom_components/asusrouter/manifest.json
  custom_components/asusrouter/router.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
  custom_components/asusrouter/update.py
  hacs.json
Labels: build

#445 Bump asusrouter to 0.16.1
  custom_components/asusrouter/manifest.json
Labels: dependencies

#446 Bump version to 0.17.1
  custom_components/asusrouter/manifest.json
Labels: build

#447 Translating v0.17.0 strings (pt-BR)
  custom_components/asusrouter/translations/pt-BR.json
Labels: translation

#448 Translating v0.17.0 strings (Spanish)
  custom_components/asusrouter/translations/es.json
Labels: translation

#449 Fix json error in translations
  custom_components/asusrouter/translations/pt-BR.json
Labels: translation

#452 Add link to the AsusRouter HA Core feature request
  README.md
  info.md
Labels: documentation

#453 Fix removing duplicated on unique_id migration
  custom_components/asusrouter/router.py
Labels: bug

#454 Migrate entities in any mode
  custom_components/asusrouter/router.py
Labels: enhancement

#456 Bump version to 0.17.2
  custom_components/asusrouter/manifest.json
Labels: build

#457 Move stable branch to 0.17.2
  README.md
  custom_components/asusrouter/manifest.json
  custom_components/asusrouter/router.py
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/pt-BR.json
  info.md
Labels: build

#458 Bump asusrouter to 0.17.0
  custom_components/asusrouter/manifest.json
Labels: dependencies

#459 Bump version to 0.17.3
  custom_components/asusrouter/manifest.json
Labels: build

#461 Bump asusrouter to 0.17.1
  custom_components/asusrouter/manifest.json
Labels: dependencies

#462 Bump version to 0.17.4
  custom_components/asusrouter/manifest.json
Labels: build

#463 Move stable branch to 0.17.4
  custom_components/asusrouter/manifest.json
Labels: build

#468 Update fr.json
  custom_components/asusrouter/translations/fr.json
Labels: translation

#473 Migrate to asusrouter 0.18.3
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/manifest.json
  custom_components/asusrouter/router.py
Labels: enhancement, backend

#475 Migrate to asusrouter 0.19.0
  custom_components/asusrouter/__init__.py
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/light.py
  custom_components/asusrouter/manifest.json
  custom_components/asusrouter/router.py
  custom_components/asusrouter/switch.py
Labels: backend

#476 Add secondary WAN info
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/const.py
Labels: enhancement, wan

#477 Remove deprecated config flow options
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
Labels: enhancement, config_flow

#478 Add access point mode
  custom_components/asusrouter/button.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/sensor.py
Labels: enhancement

#479 Bump asusrouter to 0.19.1
  custom_components/asusrouter/manifest.json
Labels: backend

#480 Update release drafter
  .github/release-drafter.yml
Labels: github

#481 Update supported devices
  README.md
Labels: documentation

#482 Links
  README.md
Labels: documentation

#483 Bump version to 0.18.0
  custom_components/asusrouter/manifest.json
Labels: build

#486 Fix bug with VPN switches
  custom_components/asusrouter/switch.py
Labels: bug

#487 Bump asusrouter to 0.19.2
  custom_components/asusrouter/manifest.json
Labels: backend

#488 Bump version to 0.18.1
  custom_components/asusrouter/manifest.json
Labels: build

#489 Bump asusrouter to 0.19.3
  custom_components/asusrouter/manifest.json
Labels: backend

#493 Fix bug in button module
  custom_components/asusrouter/button.py
Labels: bug

#495 Bump asusrouter to 0.19.4
  custom_components/asusrouter/manifest.json
Labels: backend

#496 Bump asusrouter to 0.19.5
  custom_components/asusrouter/manifest.json
Labels: backend

#497 Bump asusrouter to 0.19.6
  custom_components/asusrouter/manifest.json
Labels: backend

#499 Bump version to 0.18.2
  custom_components/asusrouter/manifest.json
Labels: build

#500 Bump asusrouter to 0.19.7
  custom_components/asusrouter/manifest.json
Labels: backend

#501 Bump version to 0.18.3
  custom_components/asusrouter/manifest.json
Labels: build
