Repository Vaskivskyi/ha-asusrouter, pull requests merged in 2023-02, with the labels that each got.

#504 Fixed typo in __init__.py
  custom_components/asusrouter/__init__.py
Labels: refactoring

#505 Fixed typo in info.md
  info.md
Labels: documentation

#507 Fix warning on HA 2023.2.x
  custom_components/asusrouter/__init__.py
Labels: bug

#508 Bump version to 0.18.4
  custom_components/asusrouter/manifest.json
Labels: build

#509 Update `__init__` module
  custom_components/asusrouter/__init__.py
  custom_components/asusrouter/const.py
Labels: refactoring

#510 Update `config_flow` module
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/device_tracker.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/switch.py
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
Labels: refactoring

#511 Update `bridge` module
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/const.py
Labels: refactoring

#512 Update `router` module
  custom_components/asusrouter/const.py
  custom_components/asusrouter/entity.py
  custom_components/asusrouter/router.py
Labels: refactoring

#513 Update `entity` module
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/button.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/entity.py
  custom_components/asusrouter/light.py
  custom_components/asusrouter/sensor.py
  custom_components/asusrouter/switch.py
  custom_components/asusrouter/update.py
Labels: refactoring

#514 Update `helpers` module
  custom_components/asusrouter/helpers.py
Labels: refactoring

#515 Update `compilers` module
  custom_components/asusrouter/compilers.py
Labels: refactoring

#516 Update all entity modules
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/button.py
  custom_components/asusrouter/light.py
  custom_components/asusrouter/sensor.py
  custom_components/asusrouter/switch.py
  custom_components/asusrouter/update.py
Labels: refactoring

#518 Improve code to fulfill HA requirements
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/button.py
  custom_components/asusrouter/compilers.py
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/dataclass.py
  custom_components/asusrouter/device_tracker.py
  custom_components/asusrouter/diagnostics.py
  custom_components/asusrouter/entity.py
  custom_components/asusrouter/light.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/sensor.py
  custom_components/asusrouter/services.yaml
  custom_components/asusrouter/switch.py
  custom_components/asusrouter/update.py
Labels: refactoring

#519 Add `Port forwarding` features
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/services.yaml
Labels: enhancement, port-forwarding

#520 Fix icons for switch entities
  custom_components/asusrouter/entity.py
Labels: bug

#521 Add `Media bridge` mode
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
Labels: enhancement

#522 Bump HA to 2023.2.0
  hacs.json
Labels: dependencies

#523 Update device list
  README.md
Labels: documentation

#524 Bump asusrouter to 0.20.0
  custom_components/asusrouter/manifest.json
Labels: backend

#525 Bump version to 0.19.0
  custom_components/asusrouter/manifest.json
Labels: build

#529 Sort manifest
  custom_components/asusrouter/manifest.json
Labels: refactoring

#530 Add missing return type
  custom_components/asusrouter/config_flow.py
Labels: refactoring

#532 Add Port Status sensors
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/const.py
Labels: enhancement

#533 Bump asusrouter to 0.20.1
  custom_components/asusrouter/manifest.json
Labels: backend

#534 Bump version to 0.20.0
  custom_components/asusrouter/manifest.json
Labels: build

#537 Update supported devices
  README.md
Labels: documentation

#540 Remove migration from before `0.17.0`
  custom_components/asusrouter/router.py
Labels: refactoring

#541 Add SSDP discovery
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/manifest.json
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
Labels: enhancement, config_flow

#542 Add discovery title
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
Labels: enhancement, config_flow

#543 Remove name step
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/router.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
Labels: enhancement, config_flow

#544 Bump asusrouter to 0.20.2
  custom_components/asusrouter/manifest.json
Labels: backend

#545 Bump version to 0.21.0
  custom_components/asusrouter/manifest.json
Labels: build

#547 Bump asusrouter to 0.20.3
  custom_components/asusrouter/manifest.json
Labels: backend

#548 Bump version to 0.21.1
  custom_components/asusrouter/manifest.json
Labels: build

#551 feat(translations) Update spanish translations
  custom_components/asusrouter/translations/es.json
Labels: translation

#552 Improve SSDP discovery
  custom_components/asusrouter/config_flow.py
Labels: enhancement, config_flow

#553 Switch discovery check to FW type
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/const.py
Labels: enhancement, config_flow

#554 Ignore discovery with no serial number
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
Labels: enhancement, config_flow

#555 Block multiple setups for single serial number
  custom_components/asusrouter/config_flow.py
  custom_components/asusrouter/strings.json
  custom_components/asusrouter/translations/cs.json
  custom_components/asusrouter/translations/en.json
  custom_components/asusrouter/translations/es.json
  custom_components/asusrouter/translations/fr.json
  custom_components/asusrouter/translations/nl.json
  custom_components/asusrouter/translations/pt-BR.json
  custom_components/asusrouter/translations/sk.json
  custom_components/asusrouter/translations/uk.json
Labels: enhancement, config_flow

#556 Remove domain name from unique_id
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/button.py
  custom_components/asusrouter/entity.py
  custom_components/asusrouter/router.py
Labels: enhancement

#559 Fix bug with repeating entities
  custom_components/asusrouter/binary_sensor.py
  custom_components/asusrouter/button.py
  custom_components/asusrouter/entity.py
  custom_components/asusrouter/light.py
  custom_components/asusrouter/sensor.py
  custom_components/asusrouter/switch.py
  custom_components/asusrouter/update.py
Labels: bug

#561 Remove deprecated sensors
  custom_components/asusrouter/bridge.py
  custom_components/asusrouter/const.py
  custom_components/asusrouter/router.py
Labels: enhancement
